name: Pre deployment validations

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Checkstyle
        run: ./mvnw checkstyle:check

  sonar-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build the project
        run: mvn clean verify

      - name: Run SonarQube Analysis
        run: mvn sonar:sonar -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}" -Dsonar.host.url=${{ vars.SONAR_HOST_URL }}" -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}" -Dsonar.token=${{ secrets.SONAR_TOKEN }}


